[build]
builder = "nixpacks"

[variables]
PHP_VERSION = "8.3"

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link || true && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
