
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100

[services.web]
start = "bash start.sh"

[services.worker]
start = "php artisan queue:work"
